### PR TITLE
Lots of changes

### PR DESCRIPTION
**Pull request by kiwi0fruit**
Updated PR according to [this](https://github.com/martinohanlon/shortcut/pull/5).

### CODE REVIEW

**Comment by martinohanlon** [comment]
merged into base for testing

**Comment by martinohanlon** [comment]
@kiwi0fruit I am going to spend a little bit of time working through these changes. Something which occurs to me now is "target_is_dir=False" - should ShortCutter work out if the target is a directory and automate this.

There also needs to be some work done so MacOS can support directories.

**Comment by martinohanlon** [comment]
Also the `shortcut` command line utility will probably need updating to reflect the changes made.

**Comment by kiwi0fruit** [comment]
>  "target_is_dir=False" - should ShortCutter work out if the target is a directory and automate this.

Maybe to move `target_is_dir=True/False` to `virtual=None/'dir'/'file'` and the existing files are determined automatically.

**Comment by kiwi0fruit** [comment]
But this will break setting `virtual`one and for all in the __init__()...

**Comment by martinohanlon** [comment]
I'll have a think about the API, but it should be simplified, there is added complexity for little benefit, from a users perspective they shouldnt need to worry about what they are creating a shortcut too.

**Comment by kiwi0fruit** [comment]
@martinohanlon I've [updated API](https://github.com/kiwi0fruit/shortcut/commit/0416c5e702a4a403035064e049fbba76a1e37163) - removed `target_is_dir`, added `virtual_type=None/'dir'/'file'`. But I guess at least one more type should added: `entry_point` which is now doesn't wort automatically.

**Comment by kiwi0fruit** [comment]
@martinohanlon It's inevitable for users to think in advance when creating shortcuts in virtual mode. So I moved (and will add more) complexity to `virtual_type`. It's optional kwarg so this should be OK.

**Comment by martinohanlon** [comment]
Good idea, 

I have been looking though the PR, here are some thoughts on the changes I will progress:

+ `virtual` mode - I will change this so it can only be set in the constructor (multiple places to set the same setting can be confusing)
  + if in `virtual` mode, and the target file or directory is not found you will have to specify the parameter `virtual_type` (file, directory) when calling "create_shortcut" or an error will be raised
+ I will look at removing the 'create temporary file' solution, I dont think you need a file in place in order to create a shortcut to it.
+ linux directory shortcuts, rather than using symlinks I will change to use .desktop files (the same as application shortcuts)
+ windows directory shortcuts, I will change to launch explorer.exe and set the working directory
+ I will add properties for `silent`, `err_file`, `virtual` so these can be changed at run time
+ I will look into macos changes

I am not convinced shortcut should be creating directories for shortcuts if they dont exist. If it is possible to create shortcuts without creating directories I will progress this. It should be up to the calling application to create any targets regardless of whether it is a file or a directory. The user of the API might not want a 'normal' directory, they might want a symlink, they might want to have the creation managed by an external process, it feels restrictive.

**Comment by martinohanlon** [comment]
I will progress these changes above.

**Comment by kiwi0fruit** [comment]
@martinohanlon What's wrong with symlinks? I bet they would work in macOS as well.

**Comment by kiwi0fruit** [comment]
@martinohanlon 
> windows directory shortcuts, I will change to launch explorer.exe and set the working directory

Why do so?

**Comment by martinohanlon** [comment]
Its not the "right" way of creating shortcuts, .desktop files have specific type for "Directory", if so you might as well use it.

**Comment by kiwi0fruit** [comment]
@martinohanlon But symlinks are the default way to create shortcuts in Ubuntu that is available from the context menu. It only might be better if .desktop files have better integration with main launcher/search. But I'm not sure if that's the case.

**Comment by martinohanlon** [comment]
@kiwi0fruit what was your intention for `err_file`? At the moment it just gets set to `stderr`, if someone was to set it to a file would it work? I dont see any mechanism for opening a different file.

**Comment by martinohanlon** [comment]
@kiwi0fruit .desktop files have significant advantages over simple symlinks, the ability to manage execution, set icons, add comments and tooltips.

**Comment by kiwi0fruit** [comment]
@martinohanlon now I create ShrtCutter with arguments:
```
error_log = io.StringIO()
sc = ShortCutter(silent=True, err_file=error_log, virtual=True)
sc.create_desktop_shortcut(pandoctools_bin)
sc.create_menu_shortcut(pandoctools_bin)
```
And create shortcuts. Each one may fail independenlty - I do not need to wrap each one in `try`/`except`. Then
```
print(error_log.getvalue(), file='log.txt')
```

**Comment by martinohanlon** [comment]
I see, so your intention was that `err_file` is a 'file' object rather than the path to a file. Ok.

**Comment by martinohanlon** [comment]
Ok, so I am going to change the interaction between silent and err_file.

+ if `silent` is True, no errors are raised and nothing is output to stderr (i.e. it is silent!)
+ if `err_file` == None (the default) nothing is output, but I will include in documentation that setting err_file to `sys.stderr` will cause errors to be written to stderr.

**Comment by martinohanlon** [comment]
or...  `silent` and `err_file` should be able to be used independently.
+ setting `silent` will silence any errors (even from the err_file)
+ setting `err_file` to `None` will result in exceptions being raised, setting to anything else will the cause errors to be routed to the `err_file`, 

So @kiwi0fruit  in your use case you would use `silent=False`, but `err_file=error_log` - as you want errors but you want them routed to a different output.

```python
error_log = io.StringIO()
sc = ShortCutter(silent=False, err_file=error_log, virtual=True)
sc.create_desktop_shortcut(pandoctools_bin)
sc.create_menu_shortcut(pandoctools_bin)
```

**Comment by kiwi0fruit** [comment]
@martinohanlon Actually there should be switches to select the following options:

* errors are raised
* errors are not raised but logged to err_file
* errors neither raised nor logged

**Comment by martinohanlon** [comment]
@kiwi0fruit - I think I just said the same.

**Comment by kiwi0fruit** [comment]
@martinohanlon Looks nice!

I foresee adding a new method. First is `sc.bin_directory()` that returns `python/Scripts` on Windows and `python/bin` on Unix.

And a new option that is wrapper for:

```
sc = ShortCutter(silent=False, err_file=error_log, virtual=True)
# virtual=True is a must as myapp exec doesn't exist yet
sc.create_desktop_shortcut(
    os.path.join(sc.bin_directory(),
                 'myapp' + ('.exe' if (if os.name == 'nt') else '')
))
```
It might be named whis way:
```
sc.create_desktop_shortcut('myapp', virtual_type='entry_point')
```

**Comment by kiwi0fruit** [comment]
@martinohanlon Actually the whole `virtual` thing is to get `sc.create_desktop_shortcut('myapp', virtual_type='entry_point')` behaviour - to add this API in future.

**Comment by martinohanlon** [comment]
re `bin_directory`, shortcut doesn't actually work this out..  It simply looks in the $PATH for folders to go and find potential executable's to shortcut too. There is some 'extra' code to look for python\Scripts in Windows because the default install doesn't put python in the $PATH.

If you want to work it out use:

```python
python_exe_path = sys.executable
python_path = os.path.dirname(python_exe_path)
scripts_path = os.path.join(python_path, "Scripts") # or "bin"
```

If its the case that `virtual` mode isnt required and the only requirement is to implement "shortcut_this_python_entry_point" (or something similar) then I would be more comfortable in doing that and removing the virtual mode stuff.

**Comment by kiwi0fruit** [comment]
Creating directories with a single kwarg is also good - instead of
try-except creation dirs then creating shortcuts.

But about executables - the only use case I see are entry-points.

пн, 4 июня 2018, 19:14 martinohanlon <notifications@github.com>:

**Comment by kiwi0fruit** [comment]
@martinohanlon Creating directories with a single kwarg is also good - instead of try-except creation dirs then creating shortcuts. But about executables - the only use case I see are entry-points.

**Comment by kiwi0fruit** [comment]
@martinohanlon What about removing virtual completely. Then adding entry_point=True to desktop and menu methods. They also work only on existing files and dirs. But also having `create_shortcut_to_dir` (as I added now). And this method has `make_target=True`.

And by the way: when specifying custom shortcut path should we create it's dir?

**Comment by kiwi0fruit** [comment]
I also suggest removing setters and getters as they are of no use now - simply have attrs names without first underscore. desktop_directory, _desktop_folder -> desktop_dir

**Comment by kiwi0fruit** [comment]
@martinohanlon

Maybe we don't need silent mode then? `err_file=None/sys.stderr/io.StringIO()` would be enough.

I also suggest removing setters and getters as they are of no use now - simply have attrs names without first underscore. desktop_directory, _desktop_folder -> desktop_dir

**Comment by kiwi0fruit** [comment]
@martinohanlon But explicit splitting `ignore_errors=True/False` and `err_file=err_file=None/sys.stderr/io.StringIO()` where None means silent mode is better in my opinion.

**Comment by martinohanlon** [comment]
Ok, I am going to mull that over.

**Comment by martinohanlon** [comment]
I am going to create some issues which document the requirements we have talked about here.

**Comment by martinohanlon** [comment]
Fyi - I have created a separate branch `0.1` to make these changes.

**Pull request merged**
